"""One-shot generator for fixtures/emails (kept for regen; committed JSON is source)."""

from __future__ import annotations

import json
from pathlib import Path

DIR = Path(__file__).resolve().parents[1] / "fixtures" / "emails"

DRAFT = "Thank you. We are reviewing your request."


def case(fid, name, frm, subject, body, expected, extra_input=None, settings=None, msg=None):
    payload = {
        "id": fid,
        "name": name,
        "input": {
            "thread_id": f"thread-eval-{fid}",
            "message_id": msg or f"msg-eval-{fid}",
            "from": frm,
            "subject": subject,
            "body": body,
            "received_at": "2026-09-04T10:00:00+00:00",
        },
        "expected": expected,
    }
    if extra_input:
        payload["input"].update(extra_input)
    if settings:
        payload["settings"] = settings
    return payload


CASES = [
    case(
        "001",
        "invoice_not_found",
        "billing@acme-supplies.com",
        "Status of INV-NOPE",
        "Where is invoice INV-NOPE for 10 EUR?",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-NOPE",
            "extracted_amount": 10.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "not_found",
            "draft_target": "invoicing",
            "to_email": "invoicing@company.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "002",
        "in_approval_on_time",
        "billing@acme-supplies.com",
        "Payment status INV-2026-0001",
        "Please confirm payment status for INV-2026-0001 amount 1250.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-0001",
            "extracted_amount": 1250.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "003",
        "posted_paid_clearing",
        "billing@acme-supplies.com",
        "Was INV-2026-0002 paid?",
        "Need proof for INV-2026-0002 / 980.50 EUR.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-0002",
            "extracted_amount": 980.50,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": True,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "004",
        "unknown_domain_quarantine",
        "phish@evil.example",
        "Invoice",
        "Pay now",
        {
            "is_ap": True,
            "intent": None,
            "ticket_status": "quarantined",
            "invoice_resolution": None,
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": False,
        },
    ),
    case(
        "005",
        "not_ap_discard",
        "billing@acme-supplies.com",
        "Team lunch",
        "Who is bringing dessert?",
        {
            "is_ap": False,
            "triage_confidence": 0.95,
            "intent": None,
            "ticket_status": "discarded",
            "invoice_resolution": None,
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": False,
        },
    ),
    case(
        "006",
        "delegate_other_operator",
        "other@vendor.com",
        "INV-2026-0001 status",
        "Please pay INV-2026-0001 1250 EUR.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-0001",
            "extracted_amount": 1250.0,
            "ticket_status": "delegated",
            "invoice_resolution": None,
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": False,
        },
    ),
    case(
        "007",
        "vat_discrepancy",
        "billing@acme-supplies.com",
        "INV-2026-0001 amount",
        "We billed 1537.50 including VAT for INV-2026-0001.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-0001",
            "extracted_amount": 1537.5,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "vat_discrepancy",
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": True,
            "vat_notes": "Extracted amount looks VAT-inclusive.",
        },
    ),
    case(
        "008",
        "multiple_sources",
        "billing@acme-supplies.com",
        "INV-MULTI",
        "Status of INV-MULTI 100 EUR.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-MULTI",
            "extracted_amount": 100.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "multiple",
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": True,
        },
    ),
    case(
        "009",
        "posted_blocked",
        "billing@acme-supplies.com",
        "INV-2026-BLOCKED",
        "Why is INV-2026-BLOCKED for 220 EUR blocked?",
        {
            "is_ap": True,
            "intent": "delay_reason",
            "extracted_ref": "INV-2026-BLOCKED",
            "extracted_amount": 220.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "payments",
            "to_email": "payments@company.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "010",
        "in_approval_overdue_owner",
        "billing@acme-supplies.com",
        "INV-2026-OVERDUE",
        "INV-2026-OVERDUE 500 EUR is late.",
        {
            "is_ap": True,
            "intent": "delay_reason",
            "extracted_ref": "INV-2026-OVERDUE",
            "extracted_amount": 500.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "approval_owners",
            "to_email": "ap-owner@company.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "011",
        "unknown_intent",
        "billing@acme-supplies.com",
        "Hello",
        "Can you help?",
        {
            "is_ap": True,
            "intent": "unknown",
            "intent_confidence": 0.9,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "not_found",
            "draft_target": "invoicing",
            "to_email": "invoicing@company.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "012",
        "low_confidence_intent",
        "billing@acme-supplies.com",
        "Maybe an invoice?",
        "Not sure what this is.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "intent_confidence": 0.2,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "not_found",
            "draft_target": "invoicing",
            "to_email": "invoicing@company.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "013",
        "delay_reason",
        "billing@acme-supplies.com",
        "Why is INV-2026-0001 delayed?",
        "Need delay reason for INV-2026-0001 1250 EUR.",
        {
            "is_ap": True,
            "intent": "delay_reason",
            "extracted_ref": "INV-2026-0001",
            "extracted_amount": 1250.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "014",
        "future_timing",
        "billing@acme-supplies.com",
        "When will INV-2026-0001 be paid?",
        "Future timing for INV-2026-0001 1250 EUR.",
        {
            "is_ap": True,
            "intent": "future_timing",
            "extracted_ref": "INV-2026-0001",
            "extracted_amount": 1250.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "015",
        "fuzzy_ref",
        "billing@acme-supplies.com",
        "INV-2026-000l",
        "Status of INV-2026-000l please.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-000l",
            "extracted_amount": None,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "multiple",
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": True,
        },
    ),
    case(
        "016",
        "amount_supplier_match",
        "billing@acme-supplies.com",
        "Unknown reference",
        "Invoice UNKNOWN-99 for 1250.50 EUR from ACME.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "UNKNOWN-99",
            "extracted_amount": 1250.50,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "017",
        "spf_dkim_fail",
        "billing@acme-supplies.com",
        "Invoice INV-2026-0001",
        "Please pay INV-2026-0001 1250.",
        {
            "is_ap": True,
            "intent": None,
            "ticket_status": "quarantined",
            "invoice_resolution": None,
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": False,
        },
        extra_input={"spf_pass": False, "dkim_pass": False},
        settings={"SPF_DKIM_ENABLED": True},
    ),
    case(
        "018",
        "posted_partial",
        "billing@acme-supplies.com",
        "INV-2026-PARTIAL",
        "Partial payment on INV-2026-PARTIAL 300 EUR.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-PARTIAL",
            "extracted_amount": 300.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": "sender",
            "to_email": "billing@acme-supplies.com",
            "attach_payment_proof": False,
            "human_action_needed": True,
            "generated_text": DRAFT,
        },
    ),
    case(
        "019",
        "paid_no_clearing",
        "billing@acme-supplies.com",
        "INV-2026-PAID-NC",
        "INV-2026-PAID-NC 150 EUR shows paid.",
        {
            "is_ap": True,
            "intent": "payment_status",
            "extracted_ref": "INV-2026-PAID-NC",
            "extracted_amount": 150.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": True,
        },
    ),
    case(
        "020",
        "overdue_no_owner",
        "billing@acme-supplies.com",
        "INV-2026-NOOWNER",
        "INV-2026-NOOWNER 400 EUR is overdue.",
        {
            "is_ap": True,
            "intent": "delay_reason",
            "extracted_ref": "INV-2026-NOOWNER",
            "extracted_amount": 400.0,
            "ticket_status": "awaiting_human",
            "invoice_resolution": "match",
            "draft_target": None,
            "to_email": None,
            "attach_payment_proof": None,
            "human_action_needed": True,
        },
    ),
]


def main() -> None:
    DIR.mkdir(parents=True, exist_ok=True)
    for item in CASES:
        name = item["name"]
        path = DIR / f"{item['id']}_{name}.json"
        path.write_text(json.dumps(item, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(CASES)} fixtures to {DIR}")


if __name__ == "__main__":
    main()
